# Generated by Django 5.1.3 on 2024-11-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileUser',
        ),
    ]
